version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "Bot"

  - package-ecosystem: "gradle"
    directory: "/"
    target-branch: "master"
    schedule:
      interval: "weekly"
      time: "09:00"
      timezone: "Asia/Kolkata"
    commit-message:
      prefix: "Bot"
    groups:
      android-gradle-plugin:
        patterns:
          - "com.android.tools:common"
          - "com.android.tools.build:gradle*"
      androidx-test:
        patterns:
          - "androidx.test*"
      androidx:
        patterns:
          - "androidx.*"