name: Build

on:
  push:
    branches: [ workflow-github, master ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: gradle

      # - name: Grant execute permission for gradlew
      #   run: chmod +x ./gradlew

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        continue-on-error: true # continue if the cache restore/upload fails
        with:
          #          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
          #          dependency-graph: generate-and-submit
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
      #          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

      #      - name: Setup Android SDK
      #        uses: android-actions/setup-android@v3
      #        with:
      #          packages: ''

      - name: Build APK
        run:  ./gradlew assembleDebug --stacktrace

      # auto-merge:
      #     runs-on: ubuntu-latest
      #     steps:
      #       - uses: actions/checkout@v2
      #       - uses: ahmadnassri/action-dependabot-auto-merge@v2
      #         with:
      #           github-token: ${{ secrets.mytoken }}

      # - name: Upload APK
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: NYTimes APK
      #     path: app/build/outputs/apk/debug/app-debug.apk
      #     tag: ${{ github.ref }}
      #     overwrite: true
