name: Delete old workflow
on:
  push:
    branches: [ workflow-github, master ]
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: "7"

permissions:
  actions: write

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@v2.1.0
        with:
          token: ${{ github.token }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.days || 7 }}