name: Delete old workflow runs
on:
  push:
    branches: [ workflow-github, master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      days:
        description: 'Number of days.'
        required: true
        default: "1"

jobs:
  del_runs:
    runs-on: ubuntu-latest
    steps:
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.AUTH_PAT }}
          repository: ${{ github.repository }}
          retain_days: ${{ github.event.inputs.days }}