name: Test

on:
  push:
    branches: [ workflow-github, master ]
jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Unit tests
        run: ./gradlew testDebugUnitTest

  instrumentation-tests:
    name: Instrumentation tests
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        # API 21 is flaky and times out.
        api-level: [29, 30, 31]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: 11

      # API 31+ emulators only have Google API, x86_64 system images.
#      - name: Get AVD info
#        uses: ./.github/actions/get-avd-info
#        id: avd-info
#        with:
#          api-level: ${{ matrix.api-level }}

      # Create a new emulator snapshot if it isn't present in the cache.
      - name: Create AVD snapshot
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: ${{ steps.avd-info.outputs.arch }}
          target: ${{ steps.avd-info.outputs.target }}
          disable-animations: false
          force-avd-creation: false
          ram-size: 4096M
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD snapshot."

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          disable-animations: true
          force-avd-creation: false
          ram-size: 4096M
          script: ./gradlew connectedDebugAndroidTest