name: Test

on:
  push:
    branches: [ workflow-github, master ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [ 29 ]
        target: [ google_apis ]
        arch: [ x86_64 ]
        channel: [ stable ]

    steps:
      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm
          ls /dev/kvm

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'zulu'
          cache: gradle

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        continue-on-error: true # continue if the cache restore/upload fails
        with:
          path: |
            ~/.gradle/caches/modules-*
            ~/.gradle/caches/jars-*
            ~/.gradle/caches/build-cache-*
      #          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}
      #          dependency-graph: generate-and-submit

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: avd-${{ matrix.api-level }} ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
      #          restore-keys: |
      #            ${{ runner.os }}-gradle-

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2.32.0
        with:
          api-level: ${{ matrix.api-level }}
          timeout-minutes: 30
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          emulator-boot-timeout: 1000
          emulator-port: 5559
          script: echo "Generated AVD snapshot for caching."

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.32.0
        with:
          api-level: ${{ matrix.api-level }}
          timeout-minutes: 30
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          emulator-boot-timeout: 1000
          emulator-port: 5561
          script: ./gradlew connectedCheck --stacktrace

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest  --stacktrace

#      - name: Upload test reports
#        if: always()
#        uses: actions/upload-artifact@v4
#        with:
#            name: test-reports-jetchat-${{ matrix.api-level }}
#            path: ${{ env.SAMPLE_PATH }}/app/build/reports
