name: Test

on:
  push:
    branches: [ workflow-github, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build the app
        run: ./gradlew build

  android_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          script: ./gradlew connectedCheck

      - name: Unit tests
        run: ./gradlew testDebugUnitTest