name: Test

on:
  push:
    branches: [ workflow-github, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'zulu'
        cache: gradle

  android_tests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 26
          script: ./gradlew connectedCheck

      - name: Unit tests
        run: ./gradlew testDebugUnitTest