name: Test

on:
  push:
    branches: [ workflow-github, master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0

#      - name: Build the app
#        run: ./gradlew build

  android_tests:
    # see https://github.com/reactivecircus/android-emulator-runner,
    # needs to run on macos as only there virtualization is available!
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2

      - name: Instrumentation Tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          api-level: 30
          script: ./gradlew connectedCheck