name: Test

on:
  push:
    branches: [ workflow-github, master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        api-level: [ 29 ]

    steps:

      - name: Checkout
        uses: actions/checkout@v2.4.0
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: gradle
          
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2.22.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.22.0
        with:
          api-level: ${{ matrix.api-level }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest  --stacktrace

