name: Test

on:
  push:
    branches: [ workflow-github, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.4.0
    - name: set up JDK 11
      uses: actions/setup-java@v2.4.0
      with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew

      - name: Run Instrumentation Tests
        run: ./gradlew connectedDebugAndroidTest --stacktrace
      - uses: reactivecircus/android-emulator-runner@v2.22.0
        with:
        api-level: 30
        arch: x86_64
        profile: Nexus 6
        disable-animations: true
        script: ./gradlew connectedCheck

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace