name: Test

on:
  push:
    branches: [ workflow-github, master ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: macos-13
    strategy:
      matrix:
        api-level: [ 30 ]
        target: [ google_apis ]
        arch: [ x86_64 ]

    steps:

      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'zulu'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      #      - name: Grant execute permission for gradlew
      #        run: chmod +x ./gradlew

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        continue-on-error: true # continue if the cache restore/upload fails
        with:
          cache-encryption-key: ${{ secrets.GradleEncryptionKey }}
          dependency-graph: generate-and-submit
      - run: gradle build --configuration-cache

      #          path: |
      #            ~/.gradle/caches/modules-*
      #            ~/.gradle/caches/jars-*
      #            ~/.gradle/caches/build-cache-*
      #          key: ${{ runner.os }}-gradle-${{ hashFiles('checksum.txt') }}

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: avd-${{ matrix.api-level }} ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2.31.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: false
          script: echo "Generated AVD snapshot for caching."

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.31.0
        with:
          api-level: ${{ matrix.api-level }}
          target: ${{ matrix.target }}
          arch: ${{ matrix.arch }}
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: ./gradlew connectedCheck --stacktrace

      - name: Unit Tests
        run: ./gradlew testDebugUnitTest  --stacktrace

