name: Test

on:
  push:
    branches: [ workflow-github, master ]
jobs:
  #  unit-tests:
  #    name: Unit tests
  #    runs-on: ubuntu-latest
  #    steps:
  #      - uses: actions/checkout@v2.4.0
  #      - uses: actions/setup-java@v2.4.0
  #        with:
  #          distribution: 'zulu'
  #          java-version: 11
  #
  #      - name: Unit tests
  #        run: ./gradlew testDebugUnitTest

  android-tests:
    runs-on: macos-latest
    strategy:
      fail-fast: true
      matrix:
        # API 21 is flaky and times out.
        api-level: [ 30 ]
    steps:
      - uses: actions/checkout@v2.4.0
      - uses: actions/setup-java@v2.4.0
        with:
          distribution: 'zulu'
          java-version: 11

      - name: Instrumentation tests
        uses: reactivecircus/android-emulator-runner@v2.21.0
        with:
          api-level: ${{ matrix.api-level }}
          disable-animations: true
          ram-size: 4096M
          script: ./gradlew connectedDebugAndroidTest