name: Test

on:
  push:
    branches: [ workflow-github, master ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ master ]
    paths-ignore:
      - '*.md'

#concurrency:
#  group: ${{ github.workflow }}-${{ github.ref }}
#  cancel-in-progress: true
env:
  cache-version: v1
  GRADLE_OPTS: "-Dorg.gradle.jvmargs=-Xmx4g -Dorg.gradle.daemon=false -Dkotlin.incremental=false"
  timeout-minutes: 15

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        api-level: [ 29 ]
        target: [ default ]
        arch: [ x86 ]
    steps:
      - name: Checkout
        uses: actions/checkout@v7        

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v6

      - name: Output target
        run: echo "The TARGET is ${{ matrix.target }}"

      - name: Unit and Robolectric UI Tests
        run: |
          SKIP_ERRORPRONE=true SKIP_JAVADOC=true ./gradlew testDebugUnitTest \
          --stacktrace --continue \
          -Dorg.gradle.workers.max=2

      - name: Release Build
        run: |
          SKIP_ERRORPRONE=true SKIP_JAVADOC=true ./gradlew :app:assembleRelease \
          --stacktrace \
          -Dorg.gradle.workers.max=2

      - name: Upload test results
        if: always()
        uses: actions/upload-artifact@v7
        with:
          name: test-results-${{ matrix.api-level }}-${{ matrix.target }}
          path: |
            **/build/reports/*
            **/build/outputs/*/connected/*



        # This is the best way I found to abort the job with an error message
      # - name: 'Notify about test failures'
      #   uses: actions/github-script@v7
      #   with:
      #     script: |
      #       core.setFailed('${{ steps.run-tests.outputs.error-message }}')
