name: Test

on:
  push:
    branches: [ workflow-github, master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
      - name: set up JDK 11
        uses: actions/setup-java@v2.5.0
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: gradle

      - name: Unit tests
        run: ./gradlew testDebugUnitTest  --stacktrace

          #  android_tests:
          #    runs-on: macos-latest
          #    steps:
          #      - uses: actions/checkout@v2
          #
          #      - name: Instrumentation Tests
          #        uses: reactivecircus/android-emulator-runner@v2
          #        with:
          #          api-level: 26
          #          script: ./gradlew connectedCheck

